// Code generated by go-swagger; DO NOT EDIT.

package policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"io"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewBulkUploadSystemPoliciesParams creates a new BulkUploadSystemPoliciesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewBulkUploadSystemPoliciesParams() *BulkUploadSystemPoliciesParams {
	return &BulkUploadSystemPoliciesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewBulkUploadSystemPoliciesParamsWithTimeout creates a new BulkUploadSystemPoliciesParams object
// with the ability to set a timeout on a request.
func NewBulkUploadSystemPoliciesParamsWithTimeout(timeout time.Duration) *BulkUploadSystemPoliciesParams {
	return &BulkUploadSystemPoliciesParams{
		timeout: timeout,
	}
}

// NewBulkUploadSystemPoliciesParamsWithContext creates a new BulkUploadSystemPoliciesParams object
// with the ability to set a context for a request.
func NewBulkUploadSystemPoliciesParamsWithContext(ctx context.Context) *BulkUploadSystemPoliciesParams {
	return &BulkUploadSystemPoliciesParams{
		Context: ctx,
	}
}

// NewBulkUploadSystemPoliciesParamsWithHTTPClient creates a new BulkUploadSystemPoliciesParams object
// with the ability to set a custom HTTPClient for a request.
func NewBulkUploadSystemPoliciesParamsWithHTTPClient(client *http.Client) *BulkUploadSystemPoliciesParams {
	return &BulkUploadSystemPoliciesParams{
		HTTPClient: client,
	}
}

/* BulkUploadSystemPoliciesParams contains all the parameters to send to the API endpoint
   for the bulk upload system policies operation.

   Typically these are written to a http.Request.
*/
type BulkUploadSystemPoliciesParams struct {

	/* Body.

	   Policy bundle

	   Format: binary
	*/
	Body io.ReadCloser

	/* System.

	   system id
	*/
	System string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the bulk upload system policies params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *BulkUploadSystemPoliciesParams) WithDefaults() *BulkUploadSystemPoliciesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the bulk upload system policies params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *BulkUploadSystemPoliciesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the bulk upload system policies params
func (o *BulkUploadSystemPoliciesParams) WithTimeout(timeout time.Duration) *BulkUploadSystemPoliciesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the bulk upload system policies params
func (o *BulkUploadSystemPoliciesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the bulk upload system policies params
func (o *BulkUploadSystemPoliciesParams) WithContext(ctx context.Context) *BulkUploadSystemPoliciesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the bulk upload system policies params
func (o *BulkUploadSystemPoliciesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the bulk upload system policies params
func (o *BulkUploadSystemPoliciesParams) WithHTTPClient(client *http.Client) *BulkUploadSystemPoliciesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the bulk upload system policies params
func (o *BulkUploadSystemPoliciesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the bulk upload system policies params
func (o *BulkUploadSystemPoliciesParams) WithBody(body io.ReadCloser) *BulkUploadSystemPoliciesParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the bulk upload system policies params
func (o *BulkUploadSystemPoliciesParams) SetBody(body io.ReadCloser) {
	o.Body = body
}

// WithSystem adds the system to the bulk upload system policies params
func (o *BulkUploadSystemPoliciesParams) WithSystem(system string) *BulkUploadSystemPoliciesParams {
	o.SetSystem(system)
	return o
}

// SetSystem adds the system to the bulk upload system policies params
func (o *BulkUploadSystemPoliciesParams) SetSystem(system string) {
	o.System = system
}

// WriteToRequest writes these params to a swagger request
func (o *BulkUploadSystemPoliciesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param system
	if err := r.SetPathParam("system", o.System); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
