// Code generated by go-swagger; DO NOT EDIT.

package timeseries

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewHandleTimeseriesMetricsParams creates a new HandleTimeseriesMetricsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewHandleTimeseriesMetricsParams() *HandleTimeseriesMetricsParams {
	return &HandleTimeseriesMetricsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewHandleTimeseriesMetricsParamsWithTimeout creates a new HandleTimeseriesMetricsParams object
// with the ability to set a timeout on a request.
func NewHandleTimeseriesMetricsParamsWithTimeout(timeout time.Duration) *HandleTimeseriesMetricsParams {
	return &HandleTimeseriesMetricsParams{
		timeout: timeout,
	}
}

// NewHandleTimeseriesMetricsParamsWithContext creates a new HandleTimeseriesMetricsParams object
// with the ability to set a context for a request.
func NewHandleTimeseriesMetricsParamsWithContext(ctx context.Context) *HandleTimeseriesMetricsParams {
	return &HandleTimeseriesMetricsParams{
		Context: ctx,
	}
}

// NewHandleTimeseriesMetricsParamsWithHTTPClient creates a new HandleTimeseriesMetricsParams object
// with the ability to set a custom HTTPClient for a request.
func NewHandleTimeseriesMetricsParamsWithHTTPClient(client *http.Client) *HandleTimeseriesMetricsParams {
	return &HandleTimeseriesMetricsParams{
		HTTPClient: client,
	}
}

/* HandleTimeseriesMetricsParams contains all the parameters to send to the API endpoint
   for the handle timeseries metrics operation.

   Typically these are written to a http.Request.
*/
type HandleTimeseriesMetricsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the handle timeseries metrics params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *HandleTimeseriesMetricsParams) WithDefaults() *HandleTimeseriesMetricsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the handle timeseries metrics params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *HandleTimeseriesMetricsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the handle timeseries metrics params
func (o *HandleTimeseriesMetricsParams) WithTimeout(timeout time.Duration) *HandleTimeseriesMetricsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the handle timeseries metrics params
func (o *HandleTimeseriesMetricsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the handle timeseries metrics params
func (o *HandleTimeseriesMetricsParams) WithContext(ctx context.Context) *HandleTimeseriesMetricsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the handle timeseries metrics params
func (o *HandleTimeseriesMetricsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the handle timeseries metrics params
func (o *HandleTimeseriesMetricsParams) WithHTTPClient(client *http.Client) *HandleTimeseriesMetricsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the handle timeseries metrics params
func (o *HandleTimeseriesMetricsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *HandleTimeseriesMetricsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
