// Code generated by go-swagger; DO NOT EDIT.

package workspace

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCommitFilesToSourceControlWorkspaceParams creates a new CommitFilesToSourceControlWorkspaceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCommitFilesToSourceControlWorkspaceParams() *CommitFilesToSourceControlWorkspaceParams {
	return &CommitFilesToSourceControlWorkspaceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCommitFilesToSourceControlWorkspaceParamsWithTimeout creates a new CommitFilesToSourceControlWorkspaceParams object
// with the ability to set a timeout on a request.
func NewCommitFilesToSourceControlWorkspaceParamsWithTimeout(timeout time.Duration) *CommitFilesToSourceControlWorkspaceParams {
	return &CommitFilesToSourceControlWorkspaceParams{
		timeout: timeout,
	}
}

// NewCommitFilesToSourceControlWorkspaceParamsWithContext creates a new CommitFilesToSourceControlWorkspaceParams object
// with the ability to set a context for a request.
func NewCommitFilesToSourceControlWorkspaceParamsWithContext(ctx context.Context) *CommitFilesToSourceControlWorkspaceParams {
	return &CommitFilesToSourceControlWorkspaceParams{
		Context: ctx,
	}
}

// NewCommitFilesToSourceControlWorkspaceParamsWithHTTPClient creates a new CommitFilesToSourceControlWorkspaceParams object
// with the ability to set a custom HTTPClient for a request.
func NewCommitFilesToSourceControlWorkspaceParamsWithHTTPClient(client *http.Client) *CommitFilesToSourceControlWorkspaceParams {
	return &CommitFilesToSourceControlWorkspaceParams{
		HTTPClient: client,
	}
}

/* CommitFilesToSourceControlWorkspaceParams contains all the parameters to send to the API endpoint
   for the commit files to source control workspace operation.

   Typically these are written to a http.Request.
*/
type CommitFilesToSourceControlWorkspaceParams struct {

	/* ID.

	   workspace id
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the commit files to source control workspace params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CommitFilesToSourceControlWorkspaceParams) WithDefaults() *CommitFilesToSourceControlWorkspaceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the commit files to source control workspace params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CommitFilesToSourceControlWorkspaceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the commit files to source control workspace params
func (o *CommitFilesToSourceControlWorkspaceParams) WithTimeout(timeout time.Duration) *CommitFilesToSourceControlWorkspaceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the commit files to source control workspace params
func (o *CommitFilesToSourceControlWorkspaceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the commit files to source control workspace params
func (o *CommitFilesToSourceControlWorkspaceParams) WithContext(ctx context.Context) *CommitFilesToSourceControlWorkspaceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the commit files to source control workspace params
func (o *CommitFilesToSourceControlWorkspaceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the commit files to source control workspace params
func (o *CommitFilesToSourceControlWorkspaceParams) WithHTTPClient(client *http.Client) *CommitFilesToSourceControlWorkspaceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the commit files to source control workspace params
func (o *CommitFilesToSourceControlWorkspaceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the commit files to source control workspace params
func (o *CommitFilesToSourceControlWorkspaceParams) WithID(id string) *CommitFilesToSourceControlWorkspaceParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the commit files to source control workspace params
func (o *CommitFilesToSourceControlWorkspaceParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *CommitFilesToSourceControlWorkspaceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
