// Code generated by go-swagger; DO NOT EDIT.

package workspace

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteUserBranchWorkspaceParams creates a new DeleteUserBranchWorkspaceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteUserBranchWorkspaceParams() *DeleteUserBranchWorkspaceParams {
	return &DeleteUserBranchWorkspaceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteUserBranchWorkspaceParamsWithTimeout creates a new DeleteUserBranchWorkspaceParams object
// with the ability to set a timeout on a request.
func NewDeleteUserBranchWorkspaceParamsWithTimeout(timeout time.Duration) *DeleteUserBranchWorkspaceParams {
	return &DeleteUserBranchWorkspaceParams{
		timeout: timeout,
	}
}

// NewDeleteUserBranchWorkspaceParamsWithContext creates a new DeleteUserBranchWorkspaceParams object
// with the ability to set a context for a request.
func NewDeleteUserBranchWorkspaceParamsWithContext(ctx context.Context) *DeleteUserBranchWorkspaceParams {
	return &DeleteUserBranchWorkspaceParams{
		Context: ctx,
	}
}

// NewDeleteUserBranchWorkspaceParamsWithHTTPClient creates a new DeleteUserBranchWorkspaceParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteUserBranchWorkspaceParamsWithHTTPClient(client *http.Client) *DeleteUserBranchWorkspaceParams {
	return &DeleteUserBranchWorkspaceParams{
		HTTPClient: client,
	}
}

/* DeleteUserBranchWorkspaceParams contains all the parameters to send to the API endpoint
   for the delete user branch workspace operation.

   Typically these are written to a http.Request.
*/
type DeleteUserBranchWorkspaceParams struct {

	/* ID.

	   workspace id
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete user branch workspace params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteUserBranchWorkspaceParams) WithDefaults() *DeleteUserBranchWorkspaceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete user branch workspace params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteUserBranchWorkspaceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete user branch workspace params
func (o *DeleteUserBranchWorkspaceParams) WithTimeout(timeout time.Duration) *DeleteUserBranchWorkspaceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete user branch workspace params
func (o *DeleteUserBranchWorkspaceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete user branch workspace params
func (o *DeleteUserBranchWorkspaceParams) WithContext(ctx context.Context) *DeleteUserBranchWorkspaceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete user branch workspace params
func (o *DeleteUserBranchWorkspaceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete user branch workspace params
func (o *DeleteUserBranchWorkspaceParams) WithHTTPClient(client *http.Client) *DeleteUserBranchWorkspaceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete user branch workspace params
func (o *DeleteUserBranchWorkspaceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete user branch workspace params
func (o *DeleteUserBranchWorkspaceParams) WithID(id string) *DeleteUserBranchWorkspaceParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete user branch workspace params
func (o *DeleteUserBranchWorkspaceParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteUserBranchWorkspaceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
