// Code generated by go-swagger; DO NOT EDIT.

package login

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// OAuth2CallbackReader is a Reader for the OAuth2Callback structure.
type OAuth2CallbackReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OAuth2CallbackReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 302:
		result := NewOAuth2CallbackFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewOAuth2CallbackFound creates a OAuth2CallbackFound with default headers values
func NewOAuth2CallbackFound() *OAuth2CallbackFound {
	return &OAuth2CallbackFound{}
}

/* OAuth2CallbackFound describes a response with status code 302, with default header values.

Redirecting
*/
type OAuth2CallbackFound struct {
}

func (o *OAuth2CallbackFound) Error() string {
	return fmt.Sprintf("[GET /v1/signup/login/oauth2/callback][%d] oAuth2CallbackFound ", 302)
}

func (o *OAuth2CallbackFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
