// Code generated by go-swagger; DO NOT EDIT.

package systems

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/mistermx/styra-go-client/pkg/models"
)

// NewCreateSystemParams creates a new CreateSystemParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateSystemParams() *CreateSystemParams {
	return &CreateSystemParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateSystemParamsWithTimeout creates a new CreateSystemParams object
// with the ability to set a timeout on a request.
func NewCreateSystemParamsWithTimeout(timeout time.Duration) *CreateSystemParams {
	return &CreateSystemParams{
		timeout: timeout,
	}
}

// NewCreateSystemParamsWithContext creates a new CreateSystemParams object
// with the ability to set a context for a request.
func NewCreateSystemParamsWithContext(ctx context.Context) *CreateSystemParams {
	return &CreateSystemParams{
		Context: ctx,
	}
}

// NewCreateSystemParamsWithHTTPClient creates a new CreateSystemParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateSystemParamsWithHTTPClient(client *http.Client) *CreateSystemParams {
	return &CreateSystemParams{
		HTTPClient: client,
	}
}

/* CreateSystemParams contains all the parameters to send to the API endpoint
   for the create system operation.

   Typically these are written to a http.Request.
*/
type CreateSystemParams struct {

	// Body.
	Body *models.SystemsV1SystemsPostRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create system params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateSystemParams) WithDefaults() *CreateSystemParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create system params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateSystemParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create system params
func (o *CreateSystemParams) WithTimeout(timeout time.Duration) *CreateSystemParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create system params
func (o *CreateSystemParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create system params
func (o *CreateSystemParams) WithContext(ctx context.Context) *CreateSystemParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create system params
func (o *CreateSystemParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create system params
func (o *CreateSystemParams) WithHTTPClient(client *http.Client) *CreateSystemParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create system params
func (o *CreateSystemParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create system params
func (o *CreateSystemParams) WithBody(body *models.SystemsV1SystemsPostRequest) *CreateSystemParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create system params
func (o *CreateSystemParams) SetBody(body *models.SystemsV1SystemsPostRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateSystemParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
