// Code generated by go-swagger; DO NOT EDIT.

package systems

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mistermx/styra-go-client/pkg/models"
)

// GetSystemAgentsReader is a Reader for the GetSystemAgents structure.
type GetSystemAgentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSystemAgentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSystemAgentsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetSystemAgentsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetSystemAgentsOK creates a GetSystemAgentsOK with default headers values
func NewGetSystemAgentsOK() *GetSystemAgentsOK {
	return &GetSystemAgentsOK{}
}

/* GetSystemAgentsOK describes a response with status code 200, with default header values.

OK
*/
type GetSystemAgentsOK struct {
	Payload *models.V1SystemsGetAgentsResponse
}

func (o *GetSystemAgentsOK) Error() string {
	return fmt.Sprintf("[GET /v1/systems/{system}/agents][%d] getSystemAgentsOK  %+v", 200, o.Payload)
}
func (o *GetSystemAgentsOK) GetPayload() *models.V1SystemsGetAgentsResponse {
	return o.Payload
}

func (o *GetSystemAgentsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1SystemsGetAgentsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSystemAgentsNotFound creates a GetSystemAgentsNotFound with default headers values
func NewGetSystemAgentsNotFound() *GetSystemAgentsNotFound {
	return &GetSystemAgentsNotFound{}
}

/* GetSystemAgentsNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetSystemAgentsNotFound struct {
	Payload *models.V1ErrorResponse
}

func (o *GetSystemAgentsNotFound) Error() string {
	return fmt.Sprintf("[GET /v1/systems/{system}/agents][%d] getSystemAgentsNotFound  %+v", 404, o.Payload)
}
func (o *GetSystemAgentsNotFound) GetPayload() *models.V1ErrorResponse {
	return o.Payload
}

func (o *GetSystemAgentsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
