// Code generated by go-swagger; DO NOT EDIT.

package logs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new logs API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for logs API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	PostDecisions(params *PostDecisionsParams, opts ...ClientOption) (*PostDecisionsOK, error)

	PostDecisionsWithPartition(params *PostDecisionsWithPartitionParams, opts ...ClientOption) (*PostDecisionsWithPartitionOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  PostDecisions posts decision logs
*/
func (a *Client) PostDecisions(params *PostDecisionsParams, opts ...ClientOption) (*PostDecisionsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostDecisionsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostDecisions",
		Method:             "POST",
		PathPattern:        "/v1/logs",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PostDecisionsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PostDecisionsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostDecisions: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  PostDecisionsWithPartition posts decision logs with partition
*/
func (a *Client) PostDecisionsWithPartition(params *PostDecisionsWithPartitionParams, opts ...ClientOption) (*PostDecisionsWithPartitionOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostDecisionsWithPartitionParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostDecisionsWithPartition",
		Method:             "POST",
		PathPattern:        "/v1/logs/{partition}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PostDecisionsWithPartitionReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PostDecisionsWithPartitionOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostDecisionsWithPartition: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
