// Code generated by go-swagger; DO NOT EDIT.

package activity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mistermx/styra-go-client/pkg/models"
)

// HandleActivityReader is a Reader for the HandleActivity structure.
type HandleActivityReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *HandleActivityReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewHandleActivityOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewHandleActivityBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewHandleActivityOK creates a HandleActivityOK with default headers values
func NewHandleActivityOK() *HandleActivityOK {
	return &HandleActivityOK{}
}

/* HandleActivityOK describes a response with status code 200, with default header values.

OK
*/
type HandleActivityOK struct {
	Payload *models.V1ActivityPostResponse
}

func (o *HandleActivityOK) Error() string {
	return fmt.Sprintf("[POST /v1/activity][%d] handleActivityOK  %+v", 200, o.Payload)
}
func (o *HandleActivityOK) GetPayload() *models.V1ActivityPostResponse {
	return o.Payload
}

func (o *HandleActivityOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1ActivityPostResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewHandleActivityBadRequest creates a HandleActivityBadRequest with default headers values
func NewHandleActivityBadRequest() *HandleActivityBadRequest {
	return &HandleActivityBadRequest{}
}

/* HandleActivityBadRequest describes a response with status code 400, with default header values.

Invalid Parameter
*/
type HandleActivityBadRequest struct {
	Payload *models.V1ErrorResponse
}

func (o *HandleActivityBadRequest) Error() string {
	return fmt.Sprintf("[POST /v1/activity][%d] handleActivityBadRequest  %+v", 400, o.Payload)
}
func (o *HandleActivityBadRequest) GetPayload() *models.V1ErrorResponse {
	return o.Payload
}

func (o *HandleActivityBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
