// Code generated by go-swagger; DO NOT EDIT.

package relay_server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRegisterClientParams creates a new RegisterClientParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRegisterClientParams() *RegisterClientParams {
	return &RegisterClientParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRegisterClientParamsWithTimeout creates a new RegisterClientParams object
// with the ability to set a timeout on a request.
func NewRegisterClientParamsWithTimeout(timeout time.Duration) *RegisterClientParams {
	return &RegisterClientParams{
		timeout: timeout,
	}
}

// NewRegisterClientParamsWithContext creates a new RegisterClientParams object
// with the ability to set a context for a request.
func NewRegisterClientParamsWithContext(ctx context.Context) *RegisterClientParams {
	return &RegisterClientParams{
		Context: ctx,
	}
}

// NewRegisterClientParamsWithHTTPClient creates a new RegisterClientParams object
// with the ability to set a custom HTTPClient for a request.
func NewRegisterClientParamsWithHTTPClient(client *http.Client) *RegisterClientParams {
	return &RegisterClientParams{
		HTTPClient: client,
	}
}

/* RegisterClientParams contains all the parameters to send to the API endpoint
   for the register client operation.

   Typically these are written to a http.Request.
*/
type RegisterClientParams struct {

	/* Key.

	   key to register the relay client with
	*/
	Key string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the register client params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RegisterClientParams) WithDefaults() *RegisterClientParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the register client params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RegisterClientParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the register client params
func (o *RegisterClientParams) WithTimeout(timeout time.Duration) *RegisterClientParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the register client params
func (o *RegisterClientParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the register client params
func (o *RegisterClientParams) WithContext(ctx context.Context) *RegisterClientParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the register client params
func (o *RegisterClientParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the register client params
func (o *RegisterClientParams) WithHTTPClient(client *http.Client) *RegisterClientParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the register client params
func (o *RegisterClientParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithKey adds the key to the register client params
func (o *RegisterClientParams) WithKey(key string) *RegisterClientParams {
	o.SetKey(key)
	return o
}

// SetKey adds the key to the register client params
func (o *RegisterClientParams) SetKey(key string) {
	o.Key = key
}

// WriteToRequest writes these params to a swagger request
func (o *RegisterClientParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param key
	if err := r.SetPathParam("key", o.Key); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
