// Code generated by go-swagger; DO NOT EDIT.

package relay_server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// RelayGETReader is a Reader for the RelayGET structure.
type RelayGETReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RelayGETReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRelayGETOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewRelayGETOK creates a RelayGETOK with default headers values
func NewRelayGETOK() *RelayGETOK {
	return &RelayGETOK{}
}

/* RelayGETOK describes a response with status code 200, with default header values.

OK
*/
type RelayGETOK struct {
}

func (o *RelayGETOK) Error() string {
	return fmt.Sprintf("[GET /v1/relay/{key}/{path}][%d] relayGETOK ", 200)
}

func (o *RelayGETOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
