// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mistermx/styra-go-client/pkg/models"
)

// CreateUpdateUserReader is a Reader for the CreateUpdateUser structure.
type CreateUpdateUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateUpdateUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateUpdateUserOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 409:
		result := NewCreateUpdateUserConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateUpdateUserOK creates a CreateUpdateUserOK with default headers values
func NewCreateUpdateUserOK() *CreateUpdateUserOK {
	return &CreateUpdateUserOK{}
}

/* CreateUpdateUserOK describes a response with status code 200, with default header values.

OK
*/
type CreateUpdateUserOK struct {
	Payload *models.UsersV1UsersPutResponse
}

func (o *CreateUpdateUserOK) Error() string {
	return fmt.Sprintf("[PUT /v1/users/{userId}][%d] createUpdateUserOK  %+v", 200, o.Payload)
}
func (o *CreateUpdateUserOK) GetPayload() *models.UsersV1UsersPutResponse {
	return o.Payload
}

func (o *CreateUpdateUserOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UsersV1UsersPutResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateUpdateUserConflict creates a CreateUpdateUserConflict with default headers values
func NewCreateUpdateUserConflict() *CreateUpdateUserConflict {
	return &CreateUpdateUserConflict{}
}

/* CreateUpdateUserConflict describes a response with status code 409, with default header values.

User already exists
*/
type CreateUpdateUserConflict struct {
	Payload *models.UsersV1UsersPutResponse
}

func (o *CreateUpdateUserConflict) Error() string {
	return fmt.Sprintf("[PUT /v1/users/{userId}][%d] createUpdateUserConflict  %+v", 409, o.Payload)
}
func (o *CreateUpdateUserConflict) GetPayload() *models.UsersV1UsersPutResponse {
	return o.Payload
}

func (o *CreateUpdateUserConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UsersV1UsersPutResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
