// Code generated by go-swagger; DO NOT EDIT.

package authz

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mistermx/styra-go-client/pkg/models"
)

// DeleteRoleBindingReader is a Reader for the DeleteRoleBinding structure.
type DeleteRoleBindingReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteRoleBindingReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteRoleBindingOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDeleteRoleBindingNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteRoleBindingOK creates a DeleteRoleBindingOK with default headers values
func NewDeleteRoleBindingOK() *DeleteRoleBindingOK {
	return &DeleteRoleBindingOK{}
}

/* DeleteRoleBindingOK describes a response with status code 200, with default header values.

OK
*/
type DeleteRoleBindingOK struct {
	Payload *models.V2RoleBindingsDeleteResponse
}

func (o *DeleteRoleBindingOK) Error() string {
	return fmt.Sprintf("[DELETE /v2/authz/rolebindings/{id}][%d] deleteRoleBindingOK  %+v", 200, o.Payload)
}
func (o *DeleteRoleBindingOK) GetPayload() *models.V2RoleBindingsDeleteResponse {
	return o.Payload
}

func (o *DeleteRoleBindingOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V2RoleBindingsDeleteResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteRoleBindingNotFound creates a DeleteRoleBindingNotFound with default headers values
func NewDeleteRoleBindingNotFound() *DeleteRoleBindingNotFound {
	return &DeleteRoleBindingNotFound{}
}

/* DeleteRoleBindingNotFound describes a response with status code 404, with default header values.

Not Found
*/
type DeleteRoleBindingNotFound struct {
	Payload *models.V1ErrorResponse
}

func (o *DeleteRoleBindingNotFound) Error() string {
	return fmt.Sprintf("[DELETE /v2/authz/rolebindings/{id}][%d] deleteRoleBindingNotFound  %+v", 404, o.Payload)
}
func (o *DeleteRoleBindingNotFound) GetPayload() *models.V1ErrorResponse {
	return o.Payload
}

func (o *DeleteRoleBindingNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
