// Code generated by go-swagger; DO NOT EDIT.

package authz

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetMigrationMarkerParams creates a new GetMigrationMarkerParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetMigrationMarkerParams() *GetMigrationMarkerParams {
	return &GetMigrationMarkerParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetMigrationMarkerParamsWithTimeout creates a new GetMigrationMarkerParams object
// with the ability to set a timeout on a request.
func NewGetMigrationMarkerParamsWithTimeout(timeout time.Duration) *GetMigrationMarkerParams {
	return &GetMigrationMarkerParams{
		timeout: timeout,
	}
}

// NewGetMigrationMarkerParamsWithContext creates a new GetMigrationMarkerParams object
// with the ability to set a context for a request.
func NewGetMigrationMarkerParamsWithContext(ctx context.Context) *GetMigrationMarkerParams {
	return &GetMigrationMarkerParams{
		Context: ctx,
	}
}

// NewGetMigrationMarkerParamsWithHTTPClient creates a new GetMigrationMarkerParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetMigrationMarkerParamsWithHTTPClient(client *http.Client) *GetMigrationMarkerParams {
	return &GetMigrationMarkerParams{
		HTTPClient: client,
	}
}

/* GetMigrationMarkerParams contains all the parameters to send to the API endpoint
   for the get migration marker operation.

   Typically these are written to a http.Request.
*/
type GetMigrationMarkerParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get migration marker params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMigrationMarkerParams) WithDefaults() *GetMigrationMarkerParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get migration marker params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMigrationMarkerParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get migration marker params
func (o *GetMigrationMarkerParams) WithTimeout(timeout time.Duration) *GetMigrationMarkerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get migration marker params
func (o *GetMigrationMarkerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get migration marker params
func (o *GetMigrationMarkerParams) WithContext(ctx context.Context) *GetMigrationMarkerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get migration marker params
func (o *GetMigrationMarkerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get migration marker params
func (o *GetMigrationMarkerParams) WithHTTPClient(client *http.Client) *GetMigrationMarkerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get migration marker params
func (o *GetMigrationMarkerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetMigrationMarkerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
