// Code generated by go-swagger; DO NOT EDIT.

package authz

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetRoleBindingV2Params creates a new GetRoleBindingV2Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetRoleBindingV2Params() *GetRoleBindingV2Params {
	return &GetRoleBindingV2Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetRoleBindingV2ParamsWithTimeout creates a new GetRoleBindingV2Params object
// with the ability to set a timeout on a request.
func NewGetRoleBindingV2ParamsWithTimeout(timeout time.Duration) *GetRoleBindingV2Params {
	return &GetRoleBindingV2Params{
		timeout: timeout,
	}
}

// NewGetRoleBindingV2ParamsWithContext creates a new GetRoleBindingV2Params object
// with the ability to set a context for a request.
func NewGetRoleBindingV2ParamsWithContext(ctx context.Context) *GetRoleBindingV2Params {
	return &GetRoleBindingV2Params{
		Context: ctx,
	}
}

// NewGetRoleBindingV2ParamsWithHTTPClient creates a new GetRoleBindingV2Params object
// with the ability to set a custom HTTPClient for a request.
func NewGetRoleBindingV2ParamsWithHTTPClient(client *http.Client) *GetRoleBindingV2Params {
	return &GetRoleBindingV2Params{
		HTTPClient: client,
	}
}

/* GetRoleBindingV2Params contains all the parameters to send to the API endpoint
   for the get role binding v2 operation.

   Typically these are written to a http.Request.
*/
type GetRoleBindingV2Params struct {

	/* ID.

	   rolebinding ID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get role binding v2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRoleBindingV2Params) WithDefaults() *GetRoleBindingV2Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get role binding v2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRoleBindingV2Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get role binding v2 params
func (o *GetRoleBindingV2Params) WithTimeout(timeout time.Duration) *GetRoleBindingV2Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get role binding v2 params
func (o *GetRoleBindingV2Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get role binding v2 params
func (o *GetRoleBindingV2Params) WithContext(ctx context.Context) *GetRoleBindingV2Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get role binding v2 params
func (o *GetRoleBindingV2Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get role binding v2 params
func (o *GetRoleBindingV2Params) WithHTTPClient(client *http.Client) *GetRoleBindingV2Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get role binding v2 params
func (o *GetRoleBindingV2Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get role binding v2 params
func (o *GetRoleBindingV2Params) WithID(id string) *GetRoleBindingV2Params {
	o.SetID(id)
	return o
}

// SetID adds the id to the get role binding v2 params
func (o *GetRoleBindingV2Params) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetRoleBindingV2Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
