// Code generated by go-swagger; DO NOT EDIT.

package authz

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mistermx/styra-go-client/pkg/models"
)

// ListRoleBindingsV1Reader is a Reader for the ListRoleBindingsV1 structure.
type ListRoleBindingsV1Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListRoleBindingsV1Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListRoleBindingsV1OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListRoleBindingsV1OK creates a ListRoleBindingsV1OK with default headers values
func NewListRoleBindingsV1OK() *ListRoleBindingsV1OK {
	return &ListRoleBindingsV1OK{}
}

/* ListRoleBindingsV1OK describes a response with status code 200, with default header values.

OK
*/
type ListRoleBindingsV1OK struct {
	Payload *models.AuthzV1RoleBindingsListResponse
}

func (o *ListRoleBindingsV1OK) Error() string {
	return fmt.Sprintf("[GET /v1/authz/rolebindings/{resourcetype}/{resource}][%d] listRoleBindingsV1OK  %+v", 200, o.Payload)
}
func (o *ListRoleBindingsV1OK) GetPayload() *models.AuthzV1RoleBindingsListResponse {
	return o.Payload
}

func (o *ListRoleBindingsV1OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AuthzV1RoleBindingsListResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
