// Code generated by go-swagger; DO NOT EDIT.

package authz

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListRoleBindingsV1Params creates a new ListRoleBindingsV1Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListRoleBindingsV1Params() *ListRoleBindingsV1Params {
	return &ListRoleBindingsV1Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewListRoleBindingsV1ParamsWithTimeout creates a new ListRoleBindingsV1Params object
// with the ability to set a timeout on a request.
func NewListRoleBindingsV1ParamsWithTimeout(timeout time.Duration) *ListRoleBindingsV1Params {
	return &ListRoleBindingsV1Params{
		timeout: timeout,
	}
}

// NewListRoleBindingsV1ParamsWithContext creates a new ListRoleBindingsV1Params object
// with the ability to set a context for a request.
func NewListRoleBindingsV1ParamsWithContext(ctx context.Context) *ListRoleBindingsV1Params {
	return &ListRoleBindingsV1Params{
		Context: ctx,
	}
}

// NewListRoleBindingsV1ParamsWithHTTPClient creates a new ListRoleBindingsV1Params object
// with the ability to set a custom HTTPClient for a request.
func NewListRoleBindingsV1ParamsWithHTTPClient(client *http.Client) *ListRoleBindingsV1Params {
	return &ListRoleBindingsV1Params{
		HTTPClient: client,
	}
}

/* ListRoleBindingsV1Params contains all the parameters to send to the API endpoint
   for the list role bindings v1 operation.

   Typically these are written to a http.Request.
*/
type ListRoleBindingsV1Params struct {

	/* Resource.

	   resource id
	*/
	Resource string

	/* Resourcetype.

	   resource type
	*/
	Resourcetype string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list role bindings v1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListRoleBindingsV1Params) WithDefaults() *ListRoleBindingsV1Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list role bindings v1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListRoleBindingsV1Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list role bindings v1 params
func (o *ListRoleBindingsV1Params) WithTimeout(timeout time.Duration) *ListRoleBindingsV1Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list role bindings v1 params
func (o *ListRoleBindingsV1Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list role bindings v1 params
func (o *ListRoleBindingsV1Params) WithContext(ctx context.Context) *ListRoleBindingsV1Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list role bindings v1 params
func (o *ListRoleBindingsV1Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list role bindings v1 params
func (o *ListRoleBindingsV1Params) WithHTTPClient(client *http.Client) *ListRoleBindingsV1Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list role bindings v1 params
func (o *ListRoleBindingsV1Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithResource adds the resource to the list role bindings v1 params
func (o *ListRoleBindingsV1Params) WithResource(resource string) *ListRoleBindingsV1Params {
	o.SetResource(resource)
	return o
}

// SetResource adds the resource to the list role bindings v1 params
func (o *ListRoleBindingsV1Params) SetResource(resource string) {
	o.Resource = resource
}

// WithResourcetype adds the resourcetype to the list role bindings v1 params
func (o *ListRoleBindingsV1Params) WithResourcetype(resourcetype string) *ListRoleBindingsV1Params {
	o.SetResourcetype(resourcetype)
	return o
}

// SetResourcetype adds the resourcetype to the list role bindings v1 params
func (o *ListRoleBindingsV1Params) SetResourcetype(resourcetype string) {
	o.Resourcetype = resourcetype
}

// WriteToRequest writes these params to a swagger request
func (o *ListRoleBindingsV1Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param resource
	if err := r.SetPathParam("resource", o.Resource); err != nil {
		return err
	}

	// path param resourcetype
	if err := r.SetPathParam("resourcetype", o.Resourcetype); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
