// Code generated by go-swagger; DO NOT EDIT.

package authz

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mistermx/styra-go-client/pkg/models"
)

// ListRoleBindingsReader is a Reader for the ListRoleBindings structure.
type ListRoleBindingsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListRoleBindingsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListRoleBindingsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListRoleBindingsOK creates a ListRoleBindingsOK with default headers values
func NewListRoleBindingsOK() *ListRoleBindingsOK {
	return &ListRoleBindingsOK{}
}

/* ListRoleBindingsOK describes a response with status code 200, with default header values.

OK
*/
type ListRoleBindingsOK struct {
	Payload *models.V2RoleBindingsListResponse
}

func (o *ListRoleBindingsOK) Error() string {
	return fmt.Sprintf("[GET /v2/authz/rolebindings][%d] listRoleBindingsOK  %+v", 200, o.Payload)
}
func (o *ListRoleBindingsOK) GetPayload() *models.V2RoleBindingsListResponse {
	return o.Payload
}

func (o *ListRoleBindingsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V2RoleBindingsListResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
