// Code generated by go-swagger; DO NOT EDIT.

package docs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetDocsParams creates a new GetDocsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetDocsParams() *GetDocsParams {
	return &GetDocsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetDocsParamsWithTimeout creates a new GetDocsParams object
// with the ability to set a timeout on a request.
func NewGetDocsParamsWithTimeout(timeout time.Duration) *GetDocsParams {
	return &GetDocsParams{
		timeout: timeout,
	}
}

// NewGetDocsParamsWithContext creates a new GetDocsParams object
// with the ability to set a context for a request.
func NewGetDocsParamsWithContext(ctx context.Context) *GetDocsParams {
	return &GetDocsParams{
		Context: ctx,
	}
}

// NewGetDocsParamsWithHTTPClient creates a new GetDocsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetDocsParamsWithHTTPClient(client *http.Client) *GetDocsParams {
	return &GetDocsParams{
		HTTPClient: client,
	}
}

/* GetDocsParams contains all the parameters to send to the API endpoint
   for the get docs operation.

   Typically these are written to a http.Request.
*/
type GetDocsParams struct {

	/* Path.

	   path
	*/
	Path string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get docs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDocsParams) WithDefaults() *GetDocsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get docs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDocsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get docs params
func (o *GetDocsParams) WithTimeout(timeout time.Duration) *GetDocsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get docs params
func (o *GetDocsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get docs params
func (o *GetDocsParams) WithContext(ctx context.Context) *GetDocsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get docs params
func (o *GetDocsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get docs params
func (o *GetDocsParams) WithHTTPClient(client *http.Client) *GetDocsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get docs params
func (o *GetDocsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPath adds the path to the get docs params
func (o *GetDocsParams) WithPath(path string) *GetDocsParams {
	o.SetPath(path)
	return o
}

// SetPath adds the path to the get docs params
func (o *GetDocsParams) SetPath(path string) {
	o.Path = path
}

// WriteToRequest writes these params to a swagger request
func (o *GetDocsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param path
	if err := r.SetPathParam("path", o.Path); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
