// Code generated by go-swagger; DO NOT EDIT.

package data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mistermx/styra-go-client/pkg/models"
)

// ListDataReader is a Reader for the ListData structure.
type ListDataReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListDataReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListDataOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewListDataNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListDataOK creates a ListDataOK with default headers values
func NewListDataOK() *ListDataOK {
	return &ListDataOK{}
}

/* ListDataOK describes a response with status code 200, with default header values.

OK
*/
type ListDataOK struct {
	Payload *models.V1DataResponse
}

func (o *ListDataOK) Error() string {
	return fmt.Sprintf("[GET /v1/data][%d] listDataOK  %+v", 200, o.Payload)
}
func (o *ListDataOK) GetPayload() *models.V1DataResponse {
	return o.Payload
}

func (o *ListDataOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1DataResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListDataNotFound creates a ListDataNotFound with default headers values
func NewListDataNotFound() *ListDataNotFound {
	return &ListDataNotFound{}
}

/* ListDataNotFound describes a response with status code 404, with default header values.

Not Found
*/
type ListDataNotFound struct {
	Payload *models.V1ErrorResponse
}

func (o *ListDataNotFound) Error() string {
	return fmt.Sprintf("[GET /v1/data][%d] listDataNotFound  %+v", 404, o.Payload)
}
func (o *ListDataNotFound) GetPayload() *models.V1ErrorResponse {
	return o.Payload
}

func (o *ListDataNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
