// Code generated by go-swagger; DO NOT EDIT.

package data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mistermx/styra-go-client/pkg/models"
)

// PatchDataReader is a Reader for the PatchData structure.
type PatchDataReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchDataReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPatchDataOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewPatchDataNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPatchDataOK creates a PatchDataOK with default headers values
func NewPatchDataOK() *PatchDataOK {
	return &PatchDataOK{}
}

/* PatchDataOK describes a response with status code 200, with default header values.

OK
*/
type PatchDataOK struct {
	Payload *models.V1DataPatchResponse
}

func (o *PatchDataOK) Error() string {
	return fmt.Sprintf("[PATCH /v1/data/{name}][%d] patchDataOK  %+v", 200, o.Payload)
}
func (o *PatchDataOK) GetPayload() *models.V1DataPatchResponse {
	return o.Payload
}

func (o *PatchDataOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1DataPatchResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPatchDataNotFound creates a PatchDataNotFound with default headers values
func NewPatchDataNotFound() *PatchDataNotFound {
	return &PatchDataNotFound{}
}

/* PatchDataNotFound describes a response with status code 404, with default header values.

Not Found
*/
type PatchDataNotFound struct {
	Payload *models.V1ErrorResponse
}

func (o *PatchDataNotFound) Error() string {
	return fmt.Sprintf("[PATCH /v1/data/{name}][%d] patchDataNotFound  %+v", 404, o.Payload)
}
func (o *PatchDataNotFound) GetPayload() *models.V1ErrorResponse {
	return o.Payload
}

func (o *PatchDataNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
