// Code generated by go-swagger; DO NOT EDIT.

package data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mistermx/styra-go-client/pkg/models"
)

// ShowDataReader is a Reader for the ShowData structure.
type ShowDataReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ShowDataReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewShowDataOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewShowDataNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewShowDataOK creates a ShowDataOK with default headers values
func NewShowDataOK() *ShowDataOK {
	return &ShowDataOK{}
}

/* ShowDataOK describes a response with status code 200, with default header values.

OK
*/
type ShowDataOK struct {
	Payload *models.DataV1DataResponse
}

func (o *ShowDataOK) Error() string {
	return fmt.Sprintf("[POST /v1/data/{name}][%d] showDataOK  %+v", 200, o.Payload)
}
func (o *ShowDataOK) GetPayload() *models.DataV1DataResponse {
	return o.Payload
}

func (o *ShowDataOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DataV1DataResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewShowDataNotFound creates a ShowDataNotFound with default headers values
func NewShowDataNotFound() *ShowDataNotFound {
	return &ShowDataNotFound{}
}

/* ShowDataNotFound describes a response with status code 404, with default header values.

Not Found
*/
type ShowDataNotFound struct {
	Payload *models.MetaV1ErrorResponse
}

func (o *ShowDataNotFound) Error() string {
	return fmt.Sprintf("[POST /v1/data/{name}][%d] showDataNotFound  %+v", 404, o.Payload)
}
func (o *ShowDataNotFound) GetPayload() *models.MetaV1ErrorResponse {
	return o.Payload
}

func (o *ShowDataNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MetaV1ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
