// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ActivityV1ActivityPostRequest activity v1 activity post request
//
// swagger:model activity.v1.ActivityPostRequest
type ActivityV1ActivityPostRequest struct {

	// audit or activity
	ClassType *string `json:"class_type,omitempty"`

	// max count of records to return: max(4096)
	Count *int32 `json:"count,omitempty"`

	// filter time range end_time
	// Format: date-time
	EndTime strfmt.DateTime `json:"end_time,omitempty"`

	// search from start(true) or end(false) of table
	Forward *bool `json:"forward,omitempty"`

	// filter on matching request_id
	RequestID string `json:"request_id,omitempty"`

	// filter time range start_time
	// Format: date-time
	StartTime strfmt.DateTime `json:"start_time,omitempty"`
}

// Validate validates this activity v1 activity post request
func (m *ActivityV1ActivityPostRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEndTime(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStartTime(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ActivityV1ActivityPostRequest) validateEndTime(formats strfmt.Registry) error {
	if swag.IsZero(m.EndTime) { // not required
		return nil
	}

	if err := validate.FormatOf("end_time", "body", "date-time", m.EndTime.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *ActivityV1ActivityPostRequest) validateStartTime(formats strfmt.Registry) error {
	if swag.IsZero(m.StartTime) { // not required
		return nil
	}

	if err := validate.FormatOf("start_time", "body", "date-time", m.StartTime.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this activity v1 activity post request based on context it is used
func (m *ActivityV1ActivityPostRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ActivityV1ActivityPostRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ActivityV1ActivityPostRequest) UnmarshalBinary(b []byte) error {
	var res ActivityV1ActivityPostRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
