// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ActivityV1RequestErrors activity v1 request errors
//
// swagger:model activity.v1.RequestErrors
type ActivityV1RequestErrors struct {

	// evaluation
	Evaluation string `json:"evaluation,omitempty"`
}

// Validate validates this activity v1 request errors
func (m *ActivityV1RequestErrors) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this activity v1 request errors based on context it is used
func (m *ActivityV1RequestErrors) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ActivityV1RequestErrors) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ActivityV1RequestErrors) UnmarshalBinary(b []byte) error {
	var res ActivityV1RequestErrors
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
