// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DatasourcesV1Poller datasources v1 poller
//
// swagger:model datasources.v1.Poller
type DatasourcesV1Poller struct {

	// polling interval
	PollingInterval *string `json:"polling_interval,omitempty"`
}

// Validate validates this datasources v1 poller
func (m *DatasourcesV1Poller) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this datasources v1 poller based on context it is used
func (m *DatasourcesV1Poller) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DatasourcesV1Poller) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DatasourcesV1Poller) UnmarshalBinary(b []byte) error {
	var res DatasourcesV1Poller
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
