// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// MetaV1RequestObject meta v1 request object
//
// swagger:model meta.v1.RequestObject
type MetaV1RequestObject interface{}
