// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MetaV1ResponseHeader meta v1 response header
//
// swagger:model meta.v1.ResponseHeader
type MetaV1ResponseHeader struct {

	// request id
	RequestID string `json:"request_id,omitempty"`
}

// Validate validates this meta v1 response header
func (m *MetaV1ResponseHeader) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this meta v1 response header based on context it is used
func (m *MetaV1ResponseHeader) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MetaV1ResponseHeader) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MetaV1ResponseHeader) UnmarshalBinary(b []byte) error {
	var res MetaV1ResponseHeader
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
