// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PoliciesV1PolicyPutResponse policies v1 policy put response
//
// swagger:model policies.v1.PolicyPutResponse
type PoliciesV1PolicyPutResponse struct {

	// request id
	RequestID string `json:"request_id,omitempty"`
}

// Validate validates this policies v1 policy put response
func (m *PoliciesV1PolicyPutResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this policies v1 policy put response based on context it is used
func (m *PoliciesV1PolicyPutResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PoliciesV1PolicyPutResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PoliciesV1PolicyPutResponse) UnmarshalBinary(b []byte) error {
	var res PoliciesV1PolicyPutResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
