// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SystemsV1AWSCredentials systems v1 a w s credentials
//
// swagger:model systems.v1.AWSCredentials
type SystemsV1AWSCredentials struct {

	// access key id and secret access key are looked under the key <name>/<access_keys>
	AccessKeys string `json:"access_keys,omitempty"`
}

// Validate validates this systems v1 a w s credentials
func (m *SystemsV1AWSCredentials) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this systems v1 a w s credentials based on context it is used
func (m *SystemsV1AWSCredentials) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SystemsV1AWSCredentials) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SystemsV1AWSCredentials) UnmarshalBinary(b []byte) error {
	var res SystemsV1AWSCredentials
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
