// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// SystemsV1ComplianceValidationNew systems v1 compliance validation new
//
// swagger:model systems.v1.ComplianceValidation.new
type SystemsV1ComplianceValidationNew interface{}
