// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// V1LogEntryInput v1 log entry input
//
// swagger:model v1.LogEntry.input
type V1LogEntryInput interface{}
