// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V2RoleBindingsPutMarkerRequest v2 role bindings put marker request
//
// swagger:model v2.RoleBindingsPutMarkerRequest
type V2RoleBindingsPutMarkerRequest struct {

	// migrated
	// Required: true
	Migrated *bool `json:"migrated"`
}

// Validate validates this v2 role bindings put marker request
func (m *V2RoleBindingsPutMarkerRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMigrated(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V2RoleBindingsPutMarkerRequest) validateMigrated(formats strfmt.Registry) error {

	if err := validate.Required("migrated", "body", m.Migrated); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this v2 role bindings put marker request based on context it is used
func (m *V2RoleBindingsPutMarkerRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V2RoleBindingsPutMarkerRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V2RoleBindingsPutMarkerRequest) UnmarshalBinary(b []byte) error {
	var res V2RoleBindingsPutMarkerRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
