// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V2RoleBindingsConfig v2 role bindings config
//
// swagger:model v2.RoleBindingsConfig
type V2RoleBindingsConfig struct {

	// metadata
	// Required: true
	Metadata *V1ObjectMeta `json:"metadata"`

	// resource filter
	// Required: true
	ResourceFilter *V2ResourceFilter `json:"resource_filter"`

	// rolebindings
	// Required: true
	Rolebindings *V2ComposedRoleBindings `json:"rolebindings"`
}

// Validate validates this v2 role bindings config
func (m *V2RoleBindingsConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMetadata(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResourceFilter(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRolebindings(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V2RoleBindingsConfig) validateMetadata(formats strfmt.Registry) error {

	if err := validate.Required("metadata", "body", m.Metadata); err != nil {
		return err
	}

	if m.Metadata != nil {
		if err := m.Metadata.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("metadata")
			}
			return err
		}
	}

	return nil
}

func (m *V2RoleBindingsConfig) validateResourceFilter(formats strfmt.Registry) error {

	if err := validate.Required("resource_filter", "body", m.ResourceFilter); err != nil {
		return err
	}

	if m.ResourceFilter != nil {
		if err := m.ResourceFilter.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("resource_filter")
			}
			return err
		}
	}

	return nil
}

func (m *V2RoleBindingsConfig) validateRolebindings(formats strfmt.Registry) error {

	if err := validate.Required("rolebindings", "body", m.Rolebindings); err != nil {
		return err
	}

	if m.Rolebindings != nil {
		if err := m.Rolebindings.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("rolebindings")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this v2 role bindings config based on the context it is used
func (m *V2RoleBindingsConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateMetadata(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateResourceFilter(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRolebindings(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V2RoleBindingsConfig) contextValidateMetadata(ctx context.Context, formats strfmt.Registry) error {

	if m.Metadata != nil {
		if err := m.Metadata.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("metadata")
			}
			return err
		}
	}

	return nil
}

func (m *V2RoleBindingsConfig) contextValidateResourceFilter(ctx context.Context, formats strfmt.Registry) error {

	if m.ResourceFilter != nil {
		if err := m.ResourceFilter.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("resource_filter")
			}
			return err
		}
	}

	return nil
}

func (m *V2RoleBindingsConfig) contextValidateRolebindings(ctx context.Context, formats strfmt.Registry) error {

	if m.Rolebindings != nil {
		if err := m.Rolebindings.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("rolebindings")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V2RoleBindingsConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V2RoleBindingsConfig) UnmarshalBinary(b []byte) error {
	var res V2RoleBindingsConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
