// Code generated by go-swagger; DO NOT EDIT.

package stacks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mistermx/styra-go-client/pkg/models"
)

// Func2Reader is a Reader for the Func2 structure.
type Func2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Func2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewFunc2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewFunc2BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewFunc2OK creates a Func2OK with default headers values
func NewFunc2OK() *Func2OK {
	return &Func2OK{}
}

/* Func2OK describes a response with status code 200, with default header values.

OK
*/
type Func2OK struct {
	Payload *models.V1VerifyConfigResponse
}

func (o *Func2OK) Error() string {
	return fmt.Sprintf("[POST /v1/stacks/source-control/verify-config][%d] func2OK  %+v", 200, o.Payload)
}
func (o *Func2OK) GetPayload() *models.V1VerifyConfigResponse {
	return o.Payload
}

func (o *Func2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1VerifyConfigResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewFunc2BadRequest creates a Func2BadRequest with default headers values
func NewFunc2BadRequest() *Func2BadRequest {
	return &Func2BadRequest{}
}

/* Func2BadRequest describes a response with status code 400, with default header values.

Invalid Config
*/
type Func2BadRequest struct {
	Payload *models.V1ErrorResponse
}

func (o *Func2BadRequest) Error() string {
	return fmt.Sprintf("[POST /v1/stacks/source-control/verify-config][%d] func2BadRequest  %+v", 400, o.Payload)
}
func (o *Func2BadRequest) GetPayload() *models.V1ErrorResponse {
	return o.Payload
}

func (o *Func2BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
