// Code generated by go-swagger; DO NOT EDIT.

package tenants

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewTenantStateParams creates a new TenantStateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewTenantStateParams() *TenantStateParams {
	return &TenantStateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewTenantStateParamsWithTimeout creates a new TenantStateParams object
// with the ability to set a timeout on a request.
func NewTenantStateParamsWithTimeout(timeout time.Duration) *TenantStateParams {
	return &TenantStateParams{
		timeout: timeout,
	}
}

// NewTenantStateParamsWithContext creates a new TenantStateParams object
// with the ability to set a context for a request.
func NewTenantStateParamsWithContext(ctx context.Context) *TenantStateParams {
	return &TenantStateParams{
		Context: ctx,
	}
}

// NewTenantStateParamsWithHTTPClient creates a new TenantStateParams object
// with the ability to set a custom HTTPClient for a request.
func NewTenantStateParamsWithHTTPClient(client *http.Client) *TenantStateParams {
	return &TenantStateParams{
		HTTPClient: client,
	}
}

/* TenantStateParams contains all the parameters to send to the API endpoint
   for the tenant state operation.

   Typically these are written to a http.Request.
*/
type TenantStateParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the tenant state params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TenantStateParams) WithDefaults() *TenantStateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the tenant state params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TenantStateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the tenant state params
func (o *TenantStateParams) WithTimeout(timeout time.Duration) *TenantStateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the tenant state params
func (o *TenantStateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the tenant state params
func (o *TenantStateParams) WithContext(ctx context.Context) *TenantStateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the tenant state params
func (o *TenantStateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the tenant state params
func (o *TenantStateParams) WithHTTPClient(client *http.Client) *TenantStateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the tenant state params
func (o *TenantStateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *TenantStateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
