// Code generated by go-swagger; DO NOT EDIT.

package bundles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mistermx/styra-go-client/pkg/models"
)

// GetPolicyBundle2Reader is a Reader for the GetPolicyBundle2 structure.
type GetPolicyBundle2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPolicyBundle2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPolicyBundle2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 304:
		result := NewGetPolicyBundle2NotModified()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetPolicyBundle2NotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetPolicyBundle2OK creates a GetPolicyBundle2OK with default headers values
func NewGetPolicyBundle2OK() *GetPolicyBundle2OK {
	return &GetPolicyBundle2OK{}
}

/* GetPolicyBundle2OK describes a response with status code 200, with default header values.

OK
*/
type GetPolicyBundle2OK struct {
	Payload []int64
}

func (o *GetPolicyBundle2OK) Error() string {
	return fmt.Sprintf("[GET /v1/bundles/{policy}][%d] getPolicyBundle2OK  %+v", 200, o.Payload)
}
func (o *GetPolicyBundle2OK) GetPayload() []int64 {
	return o.Payload
}

func (o *GetPolicyBundle2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPolicyBundle2NotModified creates a GetPolicyBundle2NotModified with default headers values
func NewGetPolicyBundle2NotModified() *GetPolicyBundle2NotModified {
	return &GetPolicyBundle2NotModified{}
}

/* GetPolicyBundle2NotModified describes a response with status code 304, with default header values.

Not Modified
*/
type GetPolicyBundle2NotModified struct {
}

func (o *GetPolicyBundle2NotModified) Error() string {
	return fmt.Sprintf("[GET /v1/bundles/{policy}][%d] getPolicyBundle2NotModified ", 304)
}

func (o *GetPolicyBundle2NotModified) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetPolicyBundle2NotFound creates a GetPolicyBundle2NotFound with default headers values
func NewGetPolicyBundle2NotFound() *GetPolicyBundle2NotFound {
	return &GetPolicyBundle2NotFound{}
}

/* GetPolicyBundle2NotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetPolicyBundle2NotFound struct {
	Payload *models.V1ErrorResponse
}

func (o *GetPolicyBundle2NotFound) Error() string {
	return fmt.Sprintf("[GET /v1/bundles/{policy}][%d] getPolicyBundle2NotFound  %+v", 404, o.Payload)
}
func (o *GetPolicyBundle2NotFound) GetPayload() *models.V1ErrorResponse {
	return o.Payload
}

func (o *GetPolicyBundle2NotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
