// Code generated by go-swagger; DO NOT EDIT.

package invitations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetInvitationParams creates a new GetInvitationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetInvitationParams() *GetInvitationParams {
	return &GetInvitationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetInvitationParamsWithTimeout creates a new GetInvitationParams object
// with the ability to set a timeout on a request.
func NewGetInvitationParamsWithTimeout(timeout time.Duration) *GetInvitationParams {
	return &GetInvitationParams{
		timeout: timeout,
	}
}

// NewGetInvitationParamsWithContext creates a new GetInvitationParams object
// with the ability to set a context for a request.
func NewGetInvitationParamsWithContext(ctx context.Context) *GetInvitationParams {
	return &GetInvitationParams{
		Context: ctx,
	}
}

// NewGetInvitationParamsWithHTTPClient creates a new GetInvitationParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetInvitationParamsWithHTTPClient(client *http.Client) *GetInvitationParams {
	return &GetInvitationParams{
		HTTPClient: client,
	}
}

/* GetInvitationParams contains all the parameters to send to the API endpoint
   for the get invitation operation.

   Typically these are written to a http.Request.
*/
type GetInvitationParams struct {

	/* ID.

	   user ID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get invitation params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInvitationParams) WithDefaults() *GetInvitationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get invitation params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInvitationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get invitation params
func (o *GetInvitationParams) WithTimeout(timeout time.Duration) *GetInvitationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get invitation params
func (o *GetInvitationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get invitation params
func (o *GetInvitationParams) WithContext(ctx context.Context) *GetInvitationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get invitation params
func (o *GetInvitationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get invitation params
func (o *GetInvitationParams) WithHTTPClient(client *http.Client) *GetInvitationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get invitation params
func (o *GetInvitationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get invitation params
func (o *GetInvitationParams) WithID(id string) *GetInvitationParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get invitation params
func (o *GetInvitationParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetInvitationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
