// Code generated by go-swagger; DO NOT EDIT.

package invitations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mistermx/styra-go-client/pkg/models"
)

// ListInvitationsReader is a Reader for the ListInvitations structure.
type ListInvitationsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListInvitationsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListInvitationsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListInvitationsOK creates a ListInvitationsOK with default headers values
func NewListInvitationsOK() *ListInvitationsOK {
	return &ListInvitationsOK{}
}

/* ListInvitationsOK describes a response with status code 200, with default header values.

OK
*/
type ListInvitationsOK struct {
	Payload *models.InvitationsV1InvitationsListResponse
}

func (o *ListInvitationsOK) Error() string {
	return fmt.Sprintf("[GET /v1/invitations][%d] listInvitationsOK  %+v", 200, o.Payload)
}
func (o *ListInvitationsOK) GetPayload() *models.InvitationsV1InvitationsListResponse {
	return o.Payload
}

func (o *ListInvitationsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InvitationsV1InvitationsListResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
