// Code generated by go-swagger; DO NOT EDIT.

package tenants_config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCreateTenantConfigParams creates a new CreateTenantConfigParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateTenantConfigParams() *CreateTenantConfigParams {
	return &CreateTenantConfigParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateTenantConfigParamsWithTimeout creates a new CreateTenantConfigParams object
// with the ability to set a timeout on a request.
func NewCreateTenantConfigParamsWithTimeout(timeout time.Duration) *CreateTenantConfigParams {
	return &CreateTenantConfigParams{
		timeout: timeout,
	}
}

// NewCreateTenantConfigParamsWithContext creates a new CreateTenantConfigParams object
// with the ability to set a context for a request.
func NewCreateTenantConfigParamsWithContext(ctx context.Context) *CreateTenantConfigParams {
	return &CreateTenantConfigParams{
		Context: ctx,
	}
}

// NewCreateTenantConfigParamsWithHTTPClient creates a new CreateTenantConfigParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateTenantConfigParamsWithHTTPClient(client *http.Client) *CreateTenantConfigParams {
	return &CreateTenantConfigParams{
		HTTPClient: client,
	}
}

/* CreateTenantConfigParams contains all the parameters to send to the API endpoint
   for the create tenant config operation.

   Typically these are written to a http.Request.
*/
type CreateTenantConfigParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create tenant config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateTenantConfigParams) WithDefaults() *CreateTenantConfigParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create tenant config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateTenantConfigParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create tenant config params
func (o *CreateTenantConfigParams) WithTimeout(timeout time.Duration) *CreateTenantConfigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create tenant config params
func (o *CreateTenantConfigParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create tenant config params
func (o *CreateTenantConfigParams) WithContext(ctx context.Context) *CreateTenantConfigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create tenant config params
func (o *CreateTenantConfigParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create tenant config params
func (o *CreateTenantConfigParams) WithHTTPClient(client *http.Client) *CreateTenantConfigParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create tenant config params
func (o *CreateTenantConfigParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *CreateTenantConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
