// Code generated by go-swagger; DO NOT EDIT.

package tenants_config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/mistermx/styra-go-client/pkg/models"
)

// NewTackleHandlerParams creates a new TackleHandlerParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewTackleHandlerParams() *TackleHandlerParams {
	return &TackleHandlerParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewTackleHandlerParamsWithTimeout creates a new TackleHandlerParams object
// with the ability to set a timeout on a request.
func NewTackleHandlerParamsWithTimeout(timeout time.Duration) *TackleHandlerParams {
	return &TackleHandlerParams{
		timeout: timeout,
	}
}

// NewTackleHandlerParamsWithContext creates a new TackleHandlerParams object
// with the ability to set a context for a request.
func NewTackleHandlerParamsWithContext(ctx context.Context) *TackleHandlerParams {
	return &TackleHandlerParams{
		Context: ctx,
	}
}

// NewTackleHandlerParamsWithHTTPClient creates a new TackleHandlerParams object
// with the ability to set a custom HTTPClient for a request.
func NewTackleHandlerParamsWithHTTPClient(client *http.Client) *TackleHandlerParams {
	return &TackleHandlerParams{
		HTTPClient: client,
	}
}

/* TackleHandlerParams contains all the parameters to send to the API endpoint
   for the tackle handler operation.

   Typically these are written to a http.Request.
*/
type TackleHandlerParams struct {

	// Body.
	Body *models.V2TackleInfo

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the tackle handler params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TackleHandlerParams) WithDefaults() *TackleHandlerParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the tackle handler params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TackleHandlerParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the tackle handler params
func (o *TackleHandlerParams) WithTimeout(timeout time.Duration) *TackleHandlerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the tackle handler params
func (o *TackleHandlerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the tackle handler params
func (o *TackleHandlerParams) WithContext(ctx context.Context) *TackleHandlerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the tackle handler params
func (o *TackleHandlerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the tackle handler params
func (o *TackleHandlerParams) WithHTTPClient(client *http.Client) *TackleHandlerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the tackle handler params
func (o *TackleHandlerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the tackle handler params
func (o *TackleHandlerParams) WithBody(body *models.V2TackleInfo) *TackleHandlerParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the tackle handler params
func (o *TackleHandlerParams) SetBody(body *models.V2TackleInfo) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *TackleHandlerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
