// Code generated by go-swagger; DO NOT EDIT.

package datasources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteDatasourceParams creates a new DeleteDatasourceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteDatasourceParams() *DeleteDatasourceParams {
	return &DeleteDatasourceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteDatasourceParamsWithTimeout creates a new DeleteDatasourceParams object
// with the ability to set a timeout on a request.
func NewDeleteDatasourceParamsWithTimeout(timeout time.Duration) *DeleteDatasourceParams {
	return &DeleteDatasourceParams{
		timeout: timeout,
	}
}

// NewDeleteDatasourceParamsWithContext creates a new DeleteDatasourceParams object
// with the ability to set a context for a request.
func NewDeleteDatasourceParamsWithContext(ctx context.Context) *DeleteDatasourceParams {
	return &DeleteDatasourceParams{
		Context: ctx,
	}
}

// NewDeleteDatasourceParamsWithHTTPClient creates a new DeleteDatasourceParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteDatasourceParamsWithHTTPClient(client *http.Client) *DeleteDatasourceParams {
	return &DeleteDatasourceParams{
		HTTPClient: client,
	}
}

/* DeleteDatasourceParams contains all the parameters to send to the API endpoint
   for the delete datasource operation.

   Typically these are written to a http.Request.
*/
type DeleteDatasourceParams struct {

	/* Datasource.

	   datasource name
	*/
	Datasource string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete datasource params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteDatasourceParams) WithDefaults() *DeleteDatasourceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete datasource params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteDatasourceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete datasource params
func (o *DeleteDatasourceParams) WithTimeout(timeout time.Duration) *DeleteDatasourceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete datasource params
func (o *DeleteDatasourceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete datasource params
func (o *DeleteDatasourceParams) WithContext(ctx context.Context) *DeleteDatasourceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete datasource params
func (o *DeleteDatasourceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete datasource params
func (o *DeleteDatasourceParams) WithHTTPClient(client *http.Client) *DeleteDatasourceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete datasource params
func (o *DeleteDatasourceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDatasource adds the datasource to the delete datasource params
func (o *DeleteDatasourceParams) WithDatasource(datasource string) *DeleteDatasourceParams {
	o.SetDatasource(datasource)
	return o
}

// SetDatasource adds the datasource to the delete datasource params
func (o *DeleteDatasourceParams) SetDatasource(datasource string) {
	o.Datasource = datasource
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteDatasourceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param datasource
	if err := r.SetPathParam("datasource", o.Datasource); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
