// Code generated by go-swagger; DO NOT EDIT.

package agents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mistermx/styra-go-client/pkg/models"
)

// UpdateAgentStatusReader is a Reader for the UpdateAgentStatus structure.
type UpdateAgentStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateAgentStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateAgentStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateAgentStatusOK creates a UpdateAgentStatusOK with default headers values
func NewUpdateAgentStatusOK() *UpdateAgentStatusOK {
	return &UpdateAgentStatusOK{}
}

/* UpdateAgentStatusOK describes a response with status code 200, with default header values.

OK
*/
type UpdateAgentStatusOK struct {
	Payload *models.StatusV1StatusPostResponse
}

func (o *UpdateAgentStatusOK) Error() string {
	return fmt.Sprintf("[PUT /v1/agents/{kind}/{id}/status][%d] updateAgentStatusOK  %+v", 200, o.Payload)
}
func (o *UpdateAgentStatusOK) GetPayload() *models.StatusV1StatusPostResponse {
	return o.Payload
}

func (o *UpdateAgentStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StatusV1StatusPostResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
