// Code generated by go-swagger; DO NOT EDIT.

package secrets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mistermx/styra-go-client/pkg/models"
)

// DeleteSecretReader is a Reader for the DeleteSecret structure.
type DeleteSecretReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteSecretReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteSecretOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteSecretOK creates a DeleteSecretOK with default headers values
func NewDeleteSecretOK() *DeleteSecretOK {
	return &DeleteSecretOK{}
}

/* DeleteSecretOK describes a response with status code 200, with default header values.

OK
*/
type DeleteSecretOK struct {
	Payload *models.V1SecretsDeleteResponse
}

func (o *DeleteSecretOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/secrets/{secretId}][%d] deleteSecretOK  %+v", 200, o.Payload)
}
func (o *DeleteSecretOK) GetPayload() *models.V1SecretsDeleteResponse {
	return o.Payload
}

func (o *DeleteSecretOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1SecretsDeleteResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
