name: CI

on:
  push:
    branches:
      - main
      - release-*
  pull_request: {}
  workflow_dispatch: {}

env:
  # Common versions
  GO_VERSION: '1.16'
  GOLANGCI_VERSION: 'v1.31'
  # DOCKER_BUILDX_VERSION: 'v0.4.2'

  # Common users. We can't run a step 'if secrets.AWS_USR != ""' but we can run
  # a step 'if env.AWS_USR' != ""', so we copy these to succinctly test whether
  # credentials have been provided before trying to run steps that need them.
  # DOCKER_USR: ${{ secrets.DOCKER_USR }}
  # AWS_USR: ${{ secrets.AWS_USR }}

jobs:
  detect-noop:
    runs-on: ubuntu-18.04
    outputs:
      noop: ${{ steps.noop.outputs.should_skip }}
    steps:
      - name: Detect No-op Changes
        id: noop
        uses: fkirc/skip-duplicate-actions@v2.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          paths_ignore: '["**.md", "**.png", "**.jpg"]'
          do_not_skip: '["workflow_dispatch", "schedule", "push"]'
          concurrent_skipping: false


  # Currently disabled because generated code contains a syntax error.
  # See https://github.com/go-swagger/go-swagger/issues/2682
  #
  # check-diff:
  #   runs-on: ubuntu-18.04
  #   needs: detect-noop
  #   if: needs.detect-noop.outputs.noop != 'true'

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         submodules: true

  #     - name: Setup Go
  #       uses: actions/setup-go@v2
  #       with:
  #         go-version: ${{ env.GO_VERSION }}

  #     - name: Find the Go Build Cache
  #       id: go
  #       run: echo "::set-output name=cache::$(go env GOCACHE)"

  #     - name: Cache the Go Build Cache
  #       uses: actions/cache@v2
  #       with:
  #         path: ${{ steps.go.outputs.cache }}
  #         key: ${{ runner.os }}-build-check-diff-${{ hashFiles('**/go.sum') }}
  #         restore-keys: ${{ runner.os }}-build-check-diff-

  #     - name: Cache Go Dependencies
  #       uses: actions/cache@v2
  #       with:
  #         path: .work/pkg
  #         key: ${{ runner.os }}-pkg-${{ hashFiles('**/go.sum') }}
  #         restore-keys: ${{ runner.os }}-pkg-

  #     # - name: Vendor Dependencies
  #     #   run: make vendor vendor.check

  #     - name: Check Diff
  #       run: make check-diff

  unit-tests:
    runs-on: ubuntu-18.04
    needs: detect-noop
    if: needs.detect-noop.outputs.noop != 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Fetch History
        run: git fetch --prune --unshallow

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Find the Go Build Cache
        id: go
        run: echo "::set-output name=cache::$(go env GOCACHE)"

      - name: Cache the Go Build Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.go.outputs.cache }}
          key: ${{ runner.os }}-build-unit-tests-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-build-unit-tests-

      - name: Cache Go Dependencies
        uses: actions/cache@v2
        with:
          path: .work/pkg
          key: ${{ runner.os }}-pkg-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-pkg-

      # - name: Vendor Dependencies
      #   run: make vendor vendor.check
